# This is a Test Report for Instacart Datasets based on Spotlight

## Data Preprocessing (to Sequence data)

In [1]:
import numpy as np
import pandas as pd
import os
import random
import math

from nltk.tokenize import word_tokenize

DEFAULT_USER_COL = "user_ids"
DEFAULT_ITEM_COL = "item_ids"
DEFAULT_ORDER_COL = "order_ids"
DEFAULT_RATING_COL = "ratings"
DEFAULT_LABEL_COL = "label"
DEFAULT_TIMESTAMP_COL = "timestamp"
DEFAULT_PREDICTION_COL = "prediction"
DEFAULT_FLAG_COL = "flag"
data_base_dir = '../../datasets/dunnhumby/raw/'

%matplotlib inline

In [2]:
transaction_data = data_base_dir + 'transaction_data.csv'
transaction_df = pd.read_csv(transaction_data)
transaction_df.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0

In [8]:
transaction_df[transaction_df.PRODUCT_ID.isin(babyfood)]

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
789,2362,27009107851,3,883859,2,1.18,436,-0.18,1959,1,0.0,0.0
794,2362,27009107851,3,929614,2,1.18,436,-0.18,1959,1,0.0,0.0
798,2362,27009107851,3,977928,2,1.18,436,-0.18,1959,1,0.0,0.0
1128,2110,27021248054,4,1135681,2,2.58,375,0.00,1705,1,0.0,0.0
1611,381,27031050789,5,946817,1,0.99,32004,0.00,1102,1,0.0,0.0
1620,381,27031050789,5,1018541,1,0.99,32004,0.00,1102,1,0.0,0.0
1639,381,27031050789,5,6533294,1,1.49,32004,0.00,1102,1,0.0,0.0
1640,381,27031050789,5,6533908,1,1.49,32004,0.00,1102,1,0.0,0.0
2228,2200,27057335598,7,864964,1,0.40,334,0.00,1201,2,0.0,0.0
2229,2200,27057335598,7,888612,1,0.40,334,0.00,1201,2,0.0,0.0
2230,2200,27057335598,7,899502,1,0.40,334,0.00,1201,2,0.0,0.0
2231,2200,27057335598,7,912019,1,0.40,334,0.00,1201,2,0.0,0.0
2232,2200,27057335598,7,989881,1,0.40,334,0.00,1201,2,0.0,0.0
2233,2200,27057335598,7,1019627,1,0.40,334,0.00,1201,2,0.0,0.0
2234,2200,27057335598,7,1061912,1,0.89,334,0.00,1201,2,0.0,0.0
2235,2200,27057335598,7,1066132,1,0.40,334,0.00,1201,2,0.0,0.0
2236,2200,27057335598,7,1066882,1,0.89,334,0.00,1201,2,0.0,0.0
2237,2200,27057335598,7,1105457,1,2.19,334,0.00,1201,2,0.0,0.0
2563,999,27057725404,7,843304,1,0.38,379,0.00,1344,2,0.0,0.0
2564,999,27057725404,7,849688,1,0.38,379,0.00,1344,2,0.0,0.0
2565,999,27057725404,7,859335,1,0.34,379,-0.04,1344,2,0.0,0.0
2566,999,27057725404,7,870128,1,0.38,379,0.00,1344,2,0.0,0.0
2571,999,27057725404,7,1135959,2,0.66,379,-0.10,1344,2,0.0,0.0
2867,2110,27069565793,8,1135681,4,5.16,375,0.00,1131,2,0.0,0.0
3304,2110,27081551501,9,886487,2,1.34,375,0.00,1516,2,0.0,0.0
3305,2110,27081551501,9,918419,2,1.34,375,0.00,1516,2,0.0,0.0
3307,2110,27081551501,9,936851,1,0.67,375,0.00,1516,2,0.0,0.0
3315,2110,27081551501,9,1040553,2,1.34,375,0.00,1516,2,0.0,0.0
3317,2110,27081551501,9,1122790,3,2.01,375,0.00,1516,2,0.0,0.0
3631,2185,27093371245,10,6904389,1,0.76,327,0.00,1607,2,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1041051,1778,31834119175,327,1019286,1,0.42,361,0.00,2057,47,0.0,0.0
1041068,1778,31834119175,327,1136988,1,0.42,361,0.00,2057,47,0.0,0.0
1041079,1778,31834119175,327,9802643,1,0.42,361,0.00,2057,47,0.0,0.0
1041176,2449,31834126825,327,1000672,1,1.19,315,0.00,1724,47,0.0,0.0
1041456,1187,31834150363,327,843304,4,1.68,381,0.00,921,47,0.0,0.0
1041461,1187,31834150363,327,1023868,4,1.68,381,0.00,921,47,0.0,0.0
1041465,1187,31834150363,327,9802643,1,0.42,381,0.00,921,47,0.0,0.0
1043238,2367,31834338128,327,1135681,1,1.29,310,0.00,1913,47,0.0,0.0
1043288,108,31834343830,327,883313,1,0.95,313,0.00,2249,47,0.0,0.0
1043321,108,31834343830,327,1107597,5,4.75,313,0.00,2249,47,0.0,0.0
1043442,1839,31834360951,327,6533437,1,0.89,420,0.00,1400,47,0.0,0.0
1043443,1839,31834360951,327,6534069,1,0.89,420,0.00,1400,47,0.0,0.0
1043444,1839,31834360951,327,6534873,1,0.89,420,0.00,1400,47,0.0,0.0
1043927,1146,31834433575,327,867065,1,1.89,304,0.00,1901,47,0.0,0.0
1043928,1146,31834433575,327,1071746,1,2.29,304,0.00,1901,47,0.0,0.0
1044221,761,31834466589,327,849032,1,1.55,343,0.00,2101,47,0.0,0.0
1044225,761,31834466589,327,904695,1,1.55,343,0.00,2101,47,0.0,0.0
1044239,761,31834466589,327,1034781,1,1.99,343,0.00,2101,47,0.0,0.0
1044245,761,31834466589,327,1085441,1,1.99,343,0.00,2101,47,0.0,0.0
1044803,1069,31868867955,328,907113,1,1.99,31782,0.00,2017,48,0.0,0.0
1044804,1069,31868867955,328,948626,2,0.82,31782,-0.08,2017,48,0.0,0.0
1044806,1069,31868867955,328,1094811,1,0.42,31782,0.00,2017,48,0.0,0.0
1044807,1069,31868867955,328,1097875,1,0.42,31782,0.00,2017,48,0.0,0.0
1045220,1385,31868916742,328,910817,1,1.79,337,0.00,2006,48,0.0,0.0
1045222,1385,31868916742,328,924305,1,2.00,337,0.00,2006,48,0.0,0.0
1045234,1385,31868916742,328,1120963,1,1.49,337,0.00,2006,48,0.0,0.0
1046534,2385,31869130721,328,995303,2,0.84,422,0.00,1121,48,0.0,0.0
1046535,2385,31869130721,328,1021108,2,0.84,422,0.00,1121,48,0.0,0.0
1046537,2385,31869130721,328,9802643,2,0.84,422,0.00,1121,48,0.0,0.0
1047085,800,31869203968,328,926465,1,1.19,298,0.00,2209,48,0.0,0.0

In [18]:
pd.merge(transaction_df[transaction_df.household_key==2385],products,on=['PRODUCT_ID'])[['household_key','COMMODITY_DESC','SUB_COMMODITY_DESC']]

,household_key,COMMODITY_DESC,SUB_COMMODITY_DESC
0,2385,BEEF,CHOICE BEEF
1,2385,BEEF,CHOICE BEEF
2,2385,TOMATOES,TOMATOES HOTHOUSE ON THE VINE
3,2385,BEEF,ROUND/LEG - STK/CHP/SLC
4,2385,HISPANIC,MEXICAN TACO TOSTADO SHELLS
5,2385,SALD DRSNG/SNDWCH SPRD,POURABLE SALAD DRESSINGS
6,2385,SALD DRSNG/SNDWCH SPRD,POURABLE SALAD DRESSINGS
7,2385,VEGETABLES - ALL OTHERS,CUCUMBERS
8,2385,VEGETABLES - ALL OTHERS,CUCUMBERS
9,2385,VEGETABLES - ALL OTHERS,CELERY
10,2385,VEGETABLES - ALL OTHERS,CELERY
11,2385,OLIVES,RIPE OLIVES
12,2385,BEEF,SELECT BEEF
13,2385,MISC. DAIRY,REFRIGERATED MEXICAN PRODUCTS
14,2385,BEEF,PRIMAL
15,2385,VEGETABLES SALAD,HEAD LETTUCE
16,2385,VEGETABLES SALAD,HEAD LETTUCE
17,2385,VEGETABLES SALAD,HEAD LETTUCE
18,2385,DELI MEATS,MEAT:HAM BULK
19,2385,DELI MEATS,MEAT:HAM BULK
20,2385,DELI MEATS,MEAT:HAM BULK
21,2385,HISPANIC,MEXICAN SEASONING MIXES
22,2385,BEANS - CANNED GLASS & MW,PREPARED BEANS - BAKED W/PORK
23,2385,BAKED BREAD/BUNS/ROLLS,MAINSTREAM WHITE BREAD
24,2385,DOMESTIC WINE,POPULAR 1.5LT WINES
25,2385,PWDR/CRYSTL DRNK MX,SOFT DRINK CANISTERS
26,2385,PWDR/CRYSTL DRNK MX,SOFT DRINK CANISTERS
27,2385,CHEESE,SHREDDED CHEESE
28,2385,HISPANIC,ORIENTAL SOY SAUCE
29,2385,TEAS,TEA BAGS & BULK TEA
...,...,...,...
497,2385,SOFT DRINKS,SOFT DRINKS 12/18&15PK CAN CAR
498,2385,SOUP,BROTH
499,2385,FRZN MEAT/MEAT DINNERS,SS ECONOMY ENTREES/DINNERS ALL
500,2385,FRZN MEAT/MEAT DINNERS,SS ECONOMY ENTREES/DINNERS ALL
501,2385,DINNER MXS:DRY,MACARONI & CHEESE DNRS
502,2385,EASTER,SEASONAL MISCELLANEOUS
503,2385,DELI MEATS,MEAT: LUNCHMEAT BULK
504,2385,SHORTENING/OIL,SOLID SHORTENING
505,2385,CANDY - PACKAGED,SEASONAL CANDY BAGS NON-CHOCOL
506,2385,BEEF,LEAN
507,2385,SUGARS/SWEETNERS,SUGAR
508,2385,CRACKERS/MISC BKD FD,CROUTONS SALAD TOPPERS BREAD
509,2385,MARGARINES,MARGARINE: TUBS AND BOWLS
510,2385,DINNER SAUSAGE,RED
511,2385,CANDY - PACKAGED,SEASONAL MISCELLANEOUS
512,2385,SALAD BAR,SALAD BAR FRESH FRUIT
513,2385,CANDY - CHECKLANE,CHEWING GUM
514,2385,FROZEN PIZZA,BURRITOS
515,2385,BABY FOODS,BABY FOOD JUNIOR ALL BRANDS
516,2385,BABY FOODS,BABY FOOD JUNIOR ALL BRANDS
517,2385,BABY FOODS,BABY FOOD JUNIOR ALL BRANDS
518,2385,BABY FOODS,BABY FOOD JUNIOR ALL BRANDS
519,2385,ICE CREAM/MILK/SHERBTS,PREMIUM
520,2385,CONVENIENT BRKFST/WHLSM SNACKS,TOASTER PASTRIES
521,2385,CONVENIENT BRKFST/WHLSM SNACKS,FRUIT SNACKS
522,2385,BAKED BREAD/BUNS/ROLLS,FRUIT/BREAKFAST BREAD
523,2385,SOUP,BROTH
524,2385,BAKING MIXES,MISCELLANEOUS PACKAGE MIXES
525,2385,DIAPERS & DISPOSABLES,BABY DIAPERS
526,2385,LAUNDRY DETERGENTS,POWDER LAUNDRY DETERGENT

In [3]:
product_data = data_base_dir + 'product.csv'
products  = pd.read_csv(product_data)
products.head()

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [6]:
babyfood = products[products.COMMODITY_DESC=='BABY FOODS'].PRODUCT_ID.to_numpy()

In [5]:
len(products.index)

92353

In [6]:
products['MANUFACTURER'].nunique(),products['DEPARTMENT'].nunique()

(6476, 44)

In [7]:
def get_bin_rep(number):
    width = int(math.ceil(np.log2(number)))
    bin_rep = []
    for _i in range(number):
        bin_rep.append([int(x) for x in np.binary_repr(_i, width=width)])
    return np.asarray(bin_rep)

get binary repesentation for MANUFACTURER

In [8]:
manu_bin_rep_list = get_bin_rep(products['MANUFACTURER'].nunique())
manufacturer_dic = {}
index = 0
for manu in products['MANUFACTURER'].unique():
    manufacturer_dic[manu]=index
    index+=1
def get_manu_vector(manufacturer):
    return manu_bin_rep_list[manufacturer_dic[manufacturer]]

get binary repesentation for DEPARTMENT

In [9]:
department_bin_rep_list = get_bin_rep(products['DEPARTMENT'].nunique())
department_dic = {}
index = 0
for product in products['DEPARTMENT'].unique():
    department_dic[product]=index
    index+=1
def get_depart_vector(department):
    return department_bin_rep_list[department_dic[department]]

In [10]:
products.head()

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [11]:
features = {}
# count = 0
# MANUFACTURER	DEPARTMENT	BRAND	COMMODITY_DESC	SUB_COMMODITY_DESC
for index,_row in products.iterrows():
    _product_id = _row['PRODUCT_ID']
    _MANUFACTURER = _row['MANUFACTURER']
    _DEPARTMENT = _row['DEPARTMENT']
#     _COMMODITY_DESC = _row['COMMODITY_DESC']
#     _SUB_COMMODITY_DESC = _row['SUB_COMMODITY_DESC']
    MANUFACTURER_vec = get_manu_vector(_MANUFACTURER)
    DEPARTMENT_vec = get_depart_vector(_DEPARTMENT)
#     words = new_str(_COMMODITY_DESC+_SUB_COMMODITY_DESC)
#     COMMODITY_vec = get_name_w2c(words)
    name_vec1 = np.concatenate((MANUFACTURER_vec, DEPARTMENT_vec))
#     name_vec = np.concatenate((COMMODITY_vec, name_vec1))
    features[_product_id] = name_vec1
len(features)

92353

In [ ]:
MANUFACTURER_vec

In [ ]:
get_name_w2c(words).shape

In [12]:
fea_out_file = data_base_dir + 'item_feature_cate.csv'
fea_out = open(fea_out_file,'w')
fea_out.write('item_id,feature\n')
for key,value in features.items():
    fea_out.write(str(key)+','+' '.join(map(str, value))+'\n')
fea_out.close()

In [ ]:
len(features[25671])

In [ ]:
for key,value in features.items():
    print()
    break

In [ ]:
map(str, [22,3])

In [ ]:
' '.join(map(str, ['1','1']))